# .github/workflows/build-on-push.yml
name: Build on Push

on:
  push:
    branches:
      - "**"   # run on any branch

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DOCKER_BUILDKIT: "1"
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    steps:
      - uses: actions/checkout@v4
      - name: Verify Docker
        run: |
          docker --version
          docker info
      - name: Build
        run: ./build.sh
      - name: Simple test
        run: ./sanity-test.sh
      - name: Units tests
        run: cd tests/units && ./run-all-tests.sh && cd ..
      - name: Basic tests
        run: cd tests/basic && ./run-basic-tests.sh && cd ..
      - name: DryRun tests
        run: cd tests/dryrun && ./run-dryrun-tests.sh && cd ..
      - name: WorkSpace Env
        run: cd tests/workspace-env && ./run-test.sh && cd ..
